apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: apps
  labels:
    app: user-service
spec:
  selector:
    app: user-service
  # NodePort 30001 maps to host port 3001 via KIND extraPortMappings
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30001
